"""
Simple Review Workflow: Reviews completed builds against plan goals.

Flow:
1. Load plan (plain text goals)
2. Read implemented code
3. Single reviewer agent checks if goals were met
4. Generate markdown report
"""
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

from core import Agent, Workflow, WorkflowResult


@dataclass
class ReviewResult:
    """Result from the review."""
    goals_met: list[str] = field(default_factory=list)
    goals_missed: list[str] = field(default_factory=list)
    issues: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    summary: str = ""


# Directories to skip when reading code
SKIP_DIRS = {".git", ".venv", "venv", "__pycache__", ".pytest_cache",
             ".mypy_cache", ".idea", ".vscode", "node_modules"}


class ReviewingWorkflow(Workflow):
    """
    Simple review workflow.

    1. Load plan goals
    2. Read code samples
    3. Ask reviewer if goals were met
    4. Generate report
    """

    def __init__(
        self,
        project_root: Path,
        output_dir: Optional[Path] = None,
    ):
        self.project_root = project_root
        output_dir = output_dir or project_root / ".orchestrator" / "specs" / "reviews"
        output_dir.mkdir(parents=True, exist_ok=True)

        super().__init__(name="Review Workflow", output_dir=output_dir)

        # Load reviewer agent
        try:
            self.register_agent(Agent.load("reviewer", project_root))
        except FileNotFoundError:
            self.console.print("[yellow]Warning: reviewer agent not found[/yellow]")

    def _load_plan(self, plan_path: Path) -> str:
        """Load plan content from file or folder."""
        if plan_path.is_dir():
            # Folder-based plan: read all .md files
            md_files = sorted(plan_path.glob("*.md"))
            if not md_files:
                return ""
            contents = []
            for md_file in md_files:
                contents.append(md_file.read_text(encoding="utf-8"))
            return "\n\n---\n\n".join(contents)
        elif plan_path.exists():
            return plan_path.read_text(encoding="utf-8")
        return ""

    def _read_code_samples(self, max_chars: int = 15000) -> str:
        """Read code samples from project."""
        code_parts = []
        total_chars = 0

        # Find Python files
        for file_path in sorted(self.project_root.rglob("*.py")):
            if any(skip in file_path.parts for skip in SKIP_DIRS):
                continue
            if total_chars >= max_chars:
                break

            try:
                content = file_path.read_text(encoding="utf-8", errors="ignore")
                rel_path = file_path.relative_to(self.project_root)

                # Truncate large files
                if len(content) > 2000:
                    content = content[:2000] + "\n... (truncated)"

                section = f"### {rel_path}\n```python\n{content}\n```"
                if total_chars + len(section) <= max_chars:
                    code_parts.append(section)
                    total_chars += len(section)
            except Exception:
                continue

        return "\n\n".join(code_parts) if code_parts else "No code files found."

    def _generate_report(self, plan_name: str, review_content: str) -> str:
        """Generate simple markdown report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

        return f"""# Review: {plan_name}

> Generated: {timestamp}

{review_content}

---
*Generated by SDLC Orchestrator*
"""

    def execute(self, plan_path_str: str) -> WorkflowResult:
        """
        Execute review workflow.

        Args:
            plan_path_str: Path to the plan file/folder
        """
        # Resolve plan path
        plan_path = Path(plan_path_str)
        if not plan_path.is_absolute():
            plan_path = self.project_root / plan_path_str

        # Try completed folder if not found
        if not plan_path.exists():
            completed = self.project_root / ".orchestrator" / "specs" / "completed" / plan_path.name
            if completed.exists():
                plan_path = completed

        if not plan_path.exists():
            return WorkflowResult(success=False, error=f"Plan not found: {plan_path}")

        self.console.print(f"[dim]Reviewing: {plan_path.name}[/dim]")

        # 1. Load plan
        self.console.print("\n[bold]Loading plan...[/bold]")
        plan_content = self._load_plan(plan_path)
        if not plan_content:
            return WorkflowResult(success=False, error="Plan is empty")

        # 2. Read code
        self.console.print("[bold]Reading code samples...[/bold]")
        code_samples = self._read_code_samples()

        # 3. Run reviewer
        self.console.print("[bold]Running review...[/bold]")
        result = self.run_agent(
            "reviewer",
            message=f"Review if this plan was implemented correctly:\n\n{plan_content[:3000]}",
            context=f"## Code Samples\n\n{code_samples}"
        )

        if not result.success:
            return WorkflowResult(success=False, error=f"Review failed: {result.error}")

        # 4. Generate and save report
        report = self._generate_report(plan_path.stem, result.content)
        report_name = f"review-{plan_path.stem}-{datetime.now().strftime('%Y%m%d-%H%M')}.md"
        output_path = self.save_output(report_name, report)

        self.console.print(f"\n[green]Review saved to: {output_path}[/green]")

        return WorkflowResult(
            success=True,
            output_file=output_path,
            steps_completed=["load_plan", "read_code", "review", "report"],
            data={"plan": plan_path.name}
        )


def main():
    """CLI entry point."""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python -m orchestrator.workflows.reviewing <plan-file>")
        sys.exit(1)

    plan_path = sys.argv[1]
    project_root = Path.cwd()

    workflow = ReviewingWorkflow(project_root=project_root)
    result = workflow.run(plan_path)

    sys.exit(0 if result.success else 1)


if __name__ == "__main__":
    main()
